/********************************************************************
* /home/fpilo/e3Tools/e3BinDump/src/e3EventCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/fpilo/e3Tools/e3BinDump/src/e3EventCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablee3EventCint();
extern void G__cpp_setup_inheritancee3EventCint();
extern void G__cpp_setup_typetablee3EventCint();
extern void G__cpp_setup_memvare3EventCint();
extern void G__cpp_setup_globale3EventCint();
extern void G__cpp_setup_memfunce3EventCint();
extern void G__cpp_setup_funce3EventCint();
extern void G__set_cpp_environmente3EventCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/fpilo/e3Tools/e3BinDump/include/e3Event.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__e3EventCintLN_TClass;
extern G__linked_taginfo G__e3EventCintLN_TBuffer;
extern G__linked_taginfo G__e3EventCintLN_TMemberInspector;
extern G__linked_taginfo G__e3EventCintLN_TObject;
extern G__linked_taginfo G__e3EventCintLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__e3EventCintLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__e3EventCintLN_string;
extern G__linked_taginfo G__e3EventCintLN_basic_stringstreamlEcharcOchar_traitslEchargRcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__e3EventCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_e3RawEvent;
extern G__linked_taginfo G__e3EventCintLN_sData;
extern G__linked_taginfo G__e3EventCintLN_dataType;
extern G__linked_taginfo G__e3EventCintLN_e3GPSData;
extern G__linked_taginfo G__e3EventCintLN_e3SORData;
extern G__linked_taginfo G__e3EventCintLN_e3GEOData;
extern G__linked_taginfo G__e3EventCintLN_e3WADData;
extern G__linked_taginfo G__e3EventCintLN_e3VWSData;
extern G__linked_taginfo G__e3EventCintLN_e3DataBlock;
extern G__linked_taginfo G__e3EventCintLN_sGlobalHeader;
extern G__linked_taginfo G__e3EventCintLN_sGlobalTrailer;
extern G__linked_taginfo G__e3EventCintLN_sTdcHeader;
extern G__linked_taginfo G__e3EventCintLN_sTdcMeasure;
extern G__linked_taginfo G__e3EventCintLN_sTdcTrailer;
extern G__linked_taginfo G__e3EventCintLN_HPTDCEvent;
extern G__linked_taginfo G__e3EventCintLN_vectorlEsTdcMeasurecOallocatorlEsTdcMeasuregRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEsTdcMeasurecOallocatorlEsTdcMeasuregRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_V1190Event;
extern G__linked_taginfo G__e3EventCintLN_vectorlEHPTDCEventcOallocatorlEHPTDCEventgRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEHPTDCEventcOallocatorlEHPTDCEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_e3RawHit;
extern G__linked_taginfo G__e3EventCintLN_e3Hit;
extern G__linked_taginfo G__e3EventCintLN_vectorlEV1190EventcOallocatorlEV1190EventgRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEV1190EventcOallocatorlEV1190EventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_vectorlEe3RawHitcOallocatorlEe3RawHitgRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEe3RawHitcOallocatorlEe3RawHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__e3EventCintLN_vectorlEe3HitcOallocatorlEe3HitgRsPgR;
extern G__linked_taginfo G__e3EventCintLN_reverse_iteratorlEvectorlEe3HitcOallocatorlEe3HitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
